# -*- coding: utf-8 -*-
"""integrais_i(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hjP1aAfQZWOioK6wjLphiVoPm79mH6fe
"""

from sympy import *
import math

init_printing(pretty_print=True)

x = Symbol('x')

Integral(cos(pi*x), (x, 0, 1))

Integral(cos(pi*x), (x, 0, 1)).doit()

Integral(cos(pi*x), (x, 0, 1)).doit().evalf(2)

S_0 = Integral(1.0 - (0.7573593128807148 * (x - 0.0)) + (0.0 * (x - 0.0)**2) - (6.62741699796952*(x-0.0)**3), (x, 0, 0.25)).doit().evalf(2)
print(S_0)

S_1 = Integral(0.7071067811865476 - (1.9999999999999998 * (x-0.25)) - (4.97056274847714*(x -0.25)**2)+ (6.627416997969518*(x-0.25)**3), (x, 0.25, 0.5)).doit().evalf(2)
print(S_1)

S_2 = Integral(6.123233995736766e-17 - (3.242640687119285 * (x-0.5)) - (1.8947806286936005e-15 * (x -0.5)**2)+ (6.627416997969523*(x-0.5)**3), (x, 0.5, 0.75)).doit().evalf(2)
print(S_2)

S_3 = Integral(-0.7071067811865475 - (2.0 * (x-0.75)) + (4.970562748477141*(x -0.75)**2) - (6.627416997969521*(x-0.75)**3), (x, 0.75, 1)).doit().evalf(2)
print(S_3)

print(S_1 + S_2 + S_3 + S_0)

SF_0 = Integral(1.0 + (0.0 * (x-0.0)) - (5.193321002610615*(x -0.0)**2)+(2.028118006381504*(x-0.0)**3), (x, 0, 0.25)).doit().evalf(2)
print(SF_0)

SF_1 = Integral(0.7071067811865476-(2.2163883751087754 * (x-0.25)) - (3.672232497824487*(x -0.25)**2)+ (4.896309997099313*(x-0.25)**3), (x, 0.25, 0.5)).doit().evalf(2)
print(SF_1)

SF_2 = Integral(6.123233995736766e-17 - (3.134446499564897 * (x-0.5)) - (2.0325621527752865e-15*(x -0.5)**2) + (4.89630999709932*(x-0.5)**3), (x, 0.5, 0.75)).doit().evalf(2)
print(SF_2)

SF_3 = Integral(-0.7071067811865475 - (2.216388375108776 * (x-0.75))+ (3.6722324978244876*(x -0.75)**2) + (2.028118006381503*(x-0.75)**3), (x, 0.75, 1)).doit().evalf(2)
print(SF_3)